#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR=$( cd $DIR/.. && pwd )

PYTESTOPT="--reuse-db -v"

if [ $? -eq 0 ]; then
    if [ "$1" = "local-sqlite" ]; then
        cd core; POLYAXON_PLATFORM_CONFIG="$ROOT_DIR/.docker/local.test.yaml" DJANGO_SETTINGS_MODULE="core.polyconf.settings" POLYAXON_STATIC_ROOT="" POLYAXON_DB_NAME="/tmp/db" py.test $PYTESTOPT ${@:2}
    elif [ "$1" = "container-sqlite" ]; then
        docker compose -f docker-compose.test.sqlite.yml run -w /core/core api py.test $PYTESTOPT ${@:2}
    elif [ "$1" = "container-pgsql" ]; then
        docker compose -f docker-compose.test.pgsql.yml run -w /core/core api py.test $PYTESTOPT ${@:2}
    fi
fi
