POLYAXON_SCHEDULER_ENABLED: true
POLYAXON_CELERY_TASK_ALWAYS_EAGER: true
POLYAXON_ENVIRONMENT: "local"
POLYAXON_SERVICE: "monolith"
POLYAXON_DEBUG: false
POLYAXON_TIME_ZONE: "Europe/Berlin"
POLYAXON_SECRET_KEY: "secret"
POLYAXON_K8S_NAMESPACE: "ns"
POLYAXON_UI_ADMIN_ENABLED: true
POLYAXON_UI_IN_SANDBOX: true
