POLYAXON_SCHEDULER_ENABLED: true
POLYAXON_CELERY_TASK_ALWAYS_EAGER: true
POLYAXON_ENVIRONMENT: "staging"
POLYAXON_SERVICE: "monolith"
POLYAXON_DEBUG: true
POLYAXON_TIME_ZONE: "Europe/Berlin"
POLYAXON_SECRET_KEY: "secret"
POLYAXON_K8S_NAMESPACE: "ns"
